config/routes.rb
FlashcardApp::Application.routes.draw do
  get "homes/index"

  resource :session, only: [:create, :new, :destroy]
  root to: "homes#index"
  resources :users, only: [:create, :new]
  resources :decks do
    resources :cards, except: :index
  end
end

app/models/card.rb
class Card < ActiveRecord::Base
  belongs_to :deck
  attr_accessible :front, :back
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :cards
  belongs_to :user
  attr_accessible :name
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :decks
  attr_accessible :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  def current_user
    if cookies[:user_id]
      user_id = cookies.signed[:user_id]
      @current_user = User.find_by_id(user_id)
    end
  end
  helper_method :current_user

  def sign_in user
    cookies.signed[:user_id] = user.id
  end

  def authenticate
    if !signed_in?
      redirect_to new_session_path
    end
  end

  def signed_in?
    current_user
  end
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def show
    @deck = find_deck
    @card = find_card
  end
  def new
    @deck = find_deck
    @card = @deck.cards.new
  end
  def create
    @deck = find_deck
    @card = @deck.cards.new(params[:card])
    @card.save
    redirect_to deck_card_path(@deck.id, @card.id)
  end
  def edit
    @deck = find_deck
    @card = find_card
  end
  def update
    @deck = find_deck
    @card = find_card
    @card.update_attributes(params[:card])
    redirect_to deck_card_path(@deck.id, @card.id)
  end
  def destroy
    @deck = find_deck
    @card = find_card
    @card.destroy
    redirect_to deck_path(@deck.id)
  end

  private

  def find_deck
    Deck.find(params[:deck_id])
  end

  def find_card
    @deck.cards.find(params[:id])
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_filter :authenticate
  def index
    @decks = current_user.decks
  end
  def show
    @deck = Deck.find(params[:id])
    @cards = @deck.cards
  end
  def new
    @deck = Deck.new
  end
  def create
    @deck = Deck.new(params[:deck])
    @deck.user_id=current_user.id
    @deck.save
    redirect_to decks_path
  end
  def edit
    @deck = Deck.find(params[:id])
  end
  def update
    @deck = Deck.find(params[:id])
    @deck.update_attributes(params[:deck])
    redirect_to @deck
  end
  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy
    redirect_to decks_path
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:session][:email])
    sign_in(user)
    redirect_to decks_path
  end

  def destroy
    cookies.delete(:user_id)
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.save
    sign_in @user
    redirect_to decks_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/decks_controller_helper.rb
module DecksControllerHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_controller_helper.rb
module UsersControllerHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/_form.html.erb
<div>
  <%= form.label :front %>
  <%= form.text_field :front %>
</div>
<div>
  <%= form.label :back %>
  <%= form.text_field :back %>
</div>

app/views/cards/edit.html.erb
<%= form_for([@deck, @card]) do |form| %>
   <%= render form %>
    <div>
      <%= form.submit("update card") %>
    </div>
<% end %>

app/views/cards/new.html.erb
<%= form_for([@deck, @card]) do |form| %>
    <%= render form %>
<div>
  <%= form.submit("create card") %>
</div>
<% end %>

app/views/cards/show.html.erb
<div>
  <%= @card.front %>
</div>
<div>
  <%= @card.back %>
</div>
<div>
  <%= link_to "return to #{@deck.name}", deck_path(@deck) %>
</div>

app/views/decks/edit.html.erb
<%= form_for(@deck) do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <%= form.submit "Edit deck" %>
<% end %>

app/views/decks/index.html.erb
Welcome
<div> <%= link_to "new deck", new_deck_path %> </div>
<%= link_to "Sign out", session_path , method: :delete %>
<% @decks.each do |deck| %>
    <div>
      <%= link_to deck.name, deck %>
      <%= link_to "Edit", edit_deck_path(deck) %>
      <%= button_to "Delete", deck, method: "delete", data: { confirm: "are you sure?" } %>
    </div>
<% end %>

app/views/decks/new.html.erb
<%= form_for(@deck) do |form| %>
    <div>
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <%= form.submit "create deck" %>
<% end %>

app/views/decks/show.html.erb
<%= link_to "Decks", decks_path %>
<div>
    <%= @deck.name %>
</div>

<% @cards.each do |card| %>
    <div>
        <%= link_to card.front, deck_card_path(@deck, card) %>
        <%= link_to "Edit", edit_deck_card_path(@deck, card) %>
        <%= button_to "Delete #{card.front}", deck_card_path(@deck, card), method: "delete", data: { confirm: "Are you sure?" } %>
    </div>
<% end %>
<%= link_to "Create new card", new_deck_card_path(@deck) %>

app/views/homes/index.html.erb
<%= link_to "Sign up", new_user_path %>
<%= link_to "Sign in", new_session_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlashcardApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<%= form_for(@user) do |form| %>
    <div>
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
      <%= form.submit "create user" %>
<% end %>

app/views/users_controller/create.html.erb
<h1>UsersController#create</h1>
<p>Find me in app/views/users_controller/create.html.erb</p>

app/views/users_controller/new.html.erb
<h1>UsersController#new</h1>
<p>Find me in app/views/users_controller/new.html.erb</p>